# Tensors, operations, Indexing and Reshaping

In [1]:
import torch

In [2]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
my_tensor.to(torch.float32), \
    torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32)

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [5]:
my_tensor.to(device = device)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
print(my_tensor.shape)

torch.Size([2, 3])


In [7]:
x = torch.empty(size=(3,3))
y = torch.zeros(size=(3,3))
x,y, x==y

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [8]:
torch.rand((3,3))

tensor([[0.8834, 0.2699, 0.5217],
        [0.2179, 0.0887, 0.2585],
        [0.1013, 0.2082, 0.5801]])

In [9]:
torch.ones((5,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
torch.eye(n=4,m=5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [11]:
torch.arange(start=0,end=5,step=1)

tensor([0, 1, 2, 3, 4])

In [12]:
torch.linspace(start=.1,end = 1, steps = 10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [13]:
torch.empty(size=(1,5)).normal_(mean=0, std = 1)

tensor([[ 0.9362,  1.0044,  0.4925, -0.3334, -0.3175]])

In [14]:
from torch.distributions import Beta

alpha = 1 
beta = 2   

# Gerar amostra aleatórias beta
amostra = Beta(alpha, beta).sample((3, 5))

print(amostra)

tensor([[0.0363, 0.2314, 0.7140, 0.6026, 0.6758],
        [0.2521, 0.2560, 0.7418, 0.7957, 0.3139],
        [0.6805, 0.4745, 0.5741, 0.2761, 0.6837]])


In [18]:
torch.diag(torch.ones(3)), \
    torch.diag(torch.tensor([1,2,3]))

(tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 tensor([[1, 0, 0],
         [0, 2, 0],
         [0, 0, 3]]))

In [19]:
torch.arange(4)

tensor([0, 1, 2, 3])