# Tensors, operations, Indexing and Reshaping

In [46]:
import torch
import numpy as np

In [47]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [48]:
my_tensor.to(torch.float32), \
    torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32)

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [49]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [50]:
my_tensor.to(device = device)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [51]:
print(my_tensor.shape)

torch.Size([2, 3])


In [52]:
x = torch.empty(size=(3,3))
y = torch.zeros(size=(3,3))
x,y, x==y

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [53]:
torch.rand((3,3))

tensor([[0.1876, 0.5100, 0.9076],
        [0.6684, 0.2875, 0.1726],
        [0.7079, 0.2816, 0.1613]])

In [54]:
torch.ones((5,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [55]:
torch.eye(n=4,m=5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [56]:
torch.arange(start=0,end=5,step=1)

tensor([0, 1, 2, 3, 4])

In [57]:
torch.linspace(start=.1,end = 1, steps = 10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [58]:
torch.empty(size=(1,5)).normal_(mean=0, std = 1)

tensor([[-0.3205,  0.5932, -1.2921,  0.6085, -0.3224]])

In [59]:
from torch.distributions import Beta

alpha = 1 
beta = 2   

# Gerar amostra aleatórias beta
amostra = Beta(alpha, beta).sample((3, 5))

print(amostra)

tensor([[0.4967, 0.3490, 0.6194, 0.5164, 0.4962],
        [0.0115, 0.1640, 0.3559, 0.5299, 0.3409],
        [0.1873, 0.4062, 0.2579, 0.4774, 0.3146]])


In [60]:
torch.diag(torch.ones(3)), \
    torch.diag(torch.tensor([1,2,3]))

(tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 tensor([[1, 0, 0],
         [0, 2, 0],
         [0, 0, 3]]))

In [61]:
tensor = torch.arange(4)
tensor.double(), tensor.bool()

(tensor([0., 1., 2., 3.], dtype=torch.float64),
 tensor([False,  True,  True,  True]))

In [62]:
torch.from_numpy(np.zeros((5,5))), \
    np.zeros((5,5))

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]], dtype=torch.float64),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [63]:
x = torch.tensor([1,2,3])
y = torch.tensor([3,4,5])


In [64]:
z = torch.empty(3)
torch.add(x,y, out = z)

tensor([4., 6., 8.])

In [65]:
z = torch.add(x,y)
z

tensor([4, 6, 8])

In [66]:
z = x + y
z

tensor([4, 6, 8])

In [67]:
z = torch.true_divide(x,y)
z

tensor([0.3333, 0.5000, 0.6000])

In [68]:
z = x/y
z

tensor([0.3333, 0.5000, 0.6000])

In [69]:
t = torch.zeros(3)
#Substitui sem criar cópia "_"
t.add_(x)

tensor([1., 2., 3.])

In [70]:
t += x
t

tensor([2., 4., 6.])

In [71]:
z = t.pow(2)
z

tensor([ 4., 16., 36.])

In [80]:
z = t**2
z

tensor([ 4., 16., 36.])

In [81]:
z > 5

tensor([False,  True,  True])

In [82]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
torch.mm(x1,x2)

tensor([[1.0543, 1.0210, 1.0285],
        [0.9366, 1.0401, 1.0472]])

In [83]:
x3 = x1.mm(x2)

In [86]:
matrix_exp = torch.rand(5,5)
matrix_exp.matrix_power(3), \
    torch.mm(matrix_exp, matrix_exp).mm(matrix_exp)

(tensor([[2.8838, 1.4063, 2.6158, 1.7453, 2.8406],
         [2.1848, 1.3264, 1.8781, 1.4104, 2.1852],
         [1.8902, 1.2007, 1.3855, 1.1338, 1.8574],
         [2.4421, 1.3954, 1.8431, 1.5760, 2.4795],
         [2.4754, 1.4657, 2.0221, 1.5975, 2.4952]]),
 tensor([[2.8838, 1.4063, 2.6158, 1.7453, 2.8406],
         [2.1848, 1.3264, 1.8781, 1.4104, 2.1852],
         [1.8902, 1.2007, 1.3855, 1.1338, 1.8574],
         [2.4421, 1.3954, 1.8431, 1.5760, 2.4795],
         [2.4754, 1.4657, 2.0221, 1.5975, 2.4952]]))

In [89]:
#multiplicação elemento a elemento 
x, y , x*y


(tensor([1, 2, 3]), tensor([3, 4, 5]), tensor([ 3,  8, 15]))

In [90]:
#produto interno
torch.dot(x,y)

tensor(26)

In [94]:
?torch.rand

Docstring:
rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor

Returns a tensor filled with random numbers from a uniform distribution
on the interval :math:`[0, 1)`

The shape of the tensor is defined by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, o

In [97]:
batch = 3
n=2
m=3
p = 4
tensor1 = torch.rand((batch, n , m))
tensor2 = torch.rand((batch, m , p))
tensor1, tensor2

(tensor([[[0.4614, 0.2882, 0.1728],
          [0.0042, 0.7656, 0.5497]],
 
         [[0.2688, 0.3369, 0.2384],
          [0.4119, 0.8581, 0.2803]],
 
         [[0.7034, 0.3048, 0.9916],
          [0.2326, 0.3866, 0.9431]]]),
 tensor([[[0.2274, 0.3822, 0.7573, 0.3020],
          [0.6956, 0.6534, 0.9031, 0.0523],
          [0.6498, 0.9579, 0.4229, 0.8809]],
 
         [[0.3366, 0.9030, 0.5979, 0.6629],
          [0.1236, 0.2964, 0.9598, 0.9096],
          [0.9608, 0.8181, 0.8580, 0.8833]],
 
         [[0.8581, 0.3982, 0.7402, 0.5847],
          [0.7542, 0.7472, 0.7287, 0.3330],
          [0.4826, 0.7994, 0.1581, 0.1384]]]))

In [98]:
torch.bmm(tensor1, tensor2)

tensor([[[0.4177, 0.5301, 0.6828, 0.3066],
         [0.8907, 1.0284, 0.9270, 0.5256]],

        [[0.3612, 0.5376, 0.6886, 0.6952],
         [0.5140, 0.8556, 1.3103, 1.3012]],

        [[1.3120, 1.3005, 0.8994, 0.6500],
         [0.9463, 1.1354, 0.6029, 0.3953]]])

### Broadcasting

In [104]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1 - x2
x1, x2, z

(tensor([[0.1473, 0.4961, 0.4105, 0.3873, 0.8635],
         [0.0202, 0.6387, 0.8328, 0.6417, 0.3094],
         [0.9902, 0.9108, 0.8381, 0.7899, 0.6245],
         [0.3363, 0.9146, 0.0149, 0.3408, 0.6808],
         [0.8379, 0.6517, 0.1930, 0.6660, 0.1193]]),
 tensor([[0.6182, 0.0681, 0.1150, 0.9283, 0.1848]]),
 tensor([[-0.4709,  0.4280,  0.2955, -0.5410,  0.6787],
         [-0.5980,  0.5707,  0.7178, -0.2866,  0.1246],
         [ 0.3720,  0.8427,  0.7232, -0.1385,  0.4397],
         [-0.2819,  0.8465, -0.1000, -0.5875,  0.4960],
         [ 0.2198,  0.5836,  0.0780, -0.2623, -0.0656]]))

In [107]:
z2 = x1 - x2.T
x1,x2.T,z2

(tensor([[0.1473, 0.4961, 0.4105, 0.3873, 0.8635],
         [0.0202, 0.6387, 0.8328, 0.6417, 0.3094],
         [0.9902, 0.9108, 0.8381, 0.7899, 0.6245],
         [0.3363, 0.9146, 0.0149, 0.3408, 0.6808],
         [0.8379, 0.6517, 0.1930, 0.6660, 0.1193]]),
 tensor([[0.6182],
         [0.0681],
         [0.1150],
         [0.9283],
         [0.1848]]),
 tensor([[-0.4709, -0.1221, -0.2077, -0.2309,  0.2453],
         [-0.0479,  0.5707,  0.7647,  0.5737,  0.2413],
         [ 0.8752,  0.7958,  0.7232,  0.6749,  0.5096],
         [-0.5920, -0.0137, -0.9134, -0.5875, -0.2475],
         [ 0.6531,  0.4668,  0.0082,  0.4812, -0.0656]]))

In [110]:
s1 = torch.sum(x1, dim = 0) # total da coluna
s2 = torch.sum(x1, dim = 1) # total da linha
x1, s1, s2

(tensor([[0.1473, 0.4961, 0.4105, 0.3873, 0.8635],
         [0.0202, 0.6387, 0.8328, 0.6417, 0.3094],
         [0.9902, 0.9108, 0.8381, 0.7899, 0.6245],
         [0.3363, 0.9146, 0.0149, 0.3408, 0.6808],
         [0.8379, 0.6517, 0.1930, 0.6660, 0.1193]]),
 tensor([2.3318, 3.6119, 2.2893, 2.8257, 2.5975]),
 tensor([2.3047, 2.4428, 4.1535, 2.2874, 2.4678]))

In [116]:
values, indices = torch.max(x1, dim = 0)
values, indices

(tensor([0.9902, 0.9146, 0.8381, 0.7899, 0.8635]), tensor([2, 3, 2, 2, 0]))

In [118]:
torch.argmax(x1, dim = 0)

tensor([2, 3, 2, 2, 0])

In [121]:
torch.mean(x1, dim = 0)

tensor([0.4664, 0.7224, 0.4579, 0.5651, 0.5195])

In [124]:
torch.eq(x1,x1+1)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [127]:
values, indices = torch.sort(x1, dim = 0, descending = False)
x1, values

(tensor([[0.1473, 0.4961, 0.4105, 0.3873, 0.8635],
         [0.0202, 0.6387, 0.8328, 0.6417, 0.3094],
         [0.9902, 0.9108, 0.8381, 0.7899, 0.6245],
         [0.3363, 0.9146, 0.0149, 0.3408, 0.6808],
         [0.8379, 0.6517, 0.1930, 0.6660, 0.1193]]),
 tensor([[0.0202, 0.4961, 0.0149, 0.3408, 0.1193],
         [0.1473, 0.6387, 0.1930, 0.3873, 0.3094],
         [0.3363, 0.6517, 0.4105, 0.6417, 0.6245],
         [0.8379, 0.9108, 0.8328, 0.6660, 0.6808],
         [0.9902, 0.9146, 0.8381, 0.7899, 0.8635]]))

In [131]:
torch.clamp(x1, min = 0.5)

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.8635],
        [0.5000, 0.6387, 0.8328, 0.6417, 0.5000],
        [0.9902, 0.9108, 0.8381, 0.7899, 0.6245],
        [0.5000, 0.9146, 0.5000, 0.5000, 0.6808],
        [0.8379, 0.6517, 0.5000, 0.6660, 0.5000]])

In [135]:
x = torch.tensor([1,0,1,1,1], dtype = torch.bool)
torch.any(x), torch.all(x)

(tensor(True), tensor(False))

In [138]:
x.max(dim = 0)

torch.return_types.max(
values=tensor(True),
indices=tensor(0))

In [ ]:
batch_size = 10
features = 25
torch.rand