# Tensors: operations, indexing and reshaping

In [152]:
import torch
import numpy as np

In [153]:
my_tensor = torch.tensor([[1,2,3],[4,5,6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [154]:
my_tensor.to(torch.float32), \
    torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32)

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [155]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [156]:
my_tensor.to(device = device)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [157]:
print(my_tensor.shape)

torch.Size([2, 3])


In [158]:
x = torch.empty(size=(3,3))
y = torch.zeros(size=(3,3))
x,y, x==y

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

In [159]:
torch.rand((3,3))

tensor([[0.6729, 0.7803, 0.5050],
        [0.7865, 0.2807, 0.0347],
        [0.0702, 0.9268, 0.1683]])

In [160]:
torch.ones((5,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [161]:
torch.eye(n=4,m=5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

In [162]:
torch.arange(start=0,end=5,step=1)

tensor([0, 1, 2, 3, 4])

In [163]:
torch.linspace(start=.1,end = 1, steps = 10)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [164]:
torch.empty(size=(1,5)).normal_(mean=0, std = 1)

tensor([[ 0.4819,  1.5586, -1.8064, -1.7738,  0.0877]])

In [165]:
from torch.distributions import Beta

alpha = 1 
beta = 2   

# Gerar amostra aleatórias beta
amostra = Beta(alpha, beta).sample((3, 5))

print(amostra)

tensor([[0.1339, 0.3923, 0.3897, 0.2355, 0.0131],
        [0.4669, 0.1225, 0.2683, 0.1726, 0.2191],
        [0.1552, 0.0188, 0.2153, 0.6070, 0.0237]])


In [166]:
torch.diag(torch.ones(3)), \
    torch.diag(torch.tensor([1,2,3]))

(tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 tensor([[1, 0, 0],
         [0, 2, 0],
         [0, 0, 3]]))

In [167]:
tensor = torch.arange(4)
tensor.double(), tensor.bool()

(tensor([0., 1., 2., 3.], dtype=torch.float64),
 tensor([False,  True,  True,  True]))

In [168]:
torch.from_numpy(np.zeros((5,5))), \
    np.zeros((5,5))

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]], dtype=torch.float64),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]))

In [169]:
x = torch.tensor([1,2,3])
y = torch.tensor([3,4,5])


In [170]:
z = torch.empty(3)
torch.add(x,y, out = z)

tensor([4., 6., 8.])

In [171]:
z = torch.add(x,y)
z

tensor([4, 6, 8])

In [172]:
z = x + y
z

tensor([4, 6, 8])

In [173]:
z = torch.true_divide(x,y)
z

tensor([0.3333, 0.5000, 0.6000])

In [174]:
z = x/y
z

tensor([0.3333, 0.5000, 0.6000])

In [175]:
t = torch.zeros(3)
#Substitui sem criar cópia "_"
t.add_(x)

tensor([1., 2., 3.])

In [176]:
t += x
t

tensor([2., 4., 6.])

In [177]:
z = t.pow(2)
z

tensor([ 4., 16., 36.])

In [178]:
z = t**2
z

tensor([ 4., 16., 36.])

In [179]:
z > 5

tensor([False,  True,  True])

In [180]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
torch.mm(x1,x2)

tensor([[1.4131, 1.5054, 1.0477],
        [0.8761, 0.9008, 0.6736]])

In [181]:
x3 = x1.mm(x2)

In [182]:
matrix_exp = torch.rand(5,5)
matrix_exp.matrix_power(3), \
    torch.mm(matrix_exp, matrix_exp).mm(matrix_exp)

(tensor([[1.8735, 1.5813, 2.0360, 1.9147, 1.8596],
         [3.3535, 2.5622, 3.1475, 3.4484, 2.9497],
         [3.3299, 2.8620, 3.4274, 3.1139, 3.3424],
         [0.8752, 0.7060, 0.8802, 0.8938, 0.8193],
         [2.5062, 2.0652, 2.5335, 2.4552, 2.4039]]),
 tensor([[1.8735, 1.5813, 2.0360, 1.9147, 1.8596],
         [3.3535, 2.5622, 3.1475, 3.4484, 2.9497],
         [3.3299, 2.8620, 3.4274, 3.1139, 3.3424],
         [0.8752, 0.7060, 0.8802, 0.8938, 0.8193],
         [2.5062, 2.0652, 2.5335, 2.4552, 2.4039]]))

In [183]:
#multiplicação elemento a elemento 
x, y , x*y


(tensor([1, 2, 3]), tensor([3, 4, 5]), tensor([ 3,  8, 15]))

In [184]:
#produto interno
torch.dot(x,y)

tensor(26)

In [185]:
?torch.rand

Docstring:
rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor

Returns a tensor filled with random numbers from a uniform distribution
on the interval :math:`[0, 1)`

The shape of the tensor is defined by the variable argument :attr:`size`.

Args:
    size (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.

Keyword args:
    generator (:class:`torch.Generator`, optional): a pseudorandom number generator for sampling
    out (Tensor, optional): the output tensor.
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, o

In [186]:
batch = 3
n=2
m=3
p = 4
tensor1 = torch.rand((batch, n , m))
tensor2 = torch.rand((batch, m , p))
tensor1, tensor2

(tensor([[[0.2370, 0.7802, 0.5054],
          [0.0709, 0.2151, 0.4990]],
 
         [[0.8822, 0.9386, 0.9140],
          [0.3976, 0.0968, 0.0620]],
 
         [[0.9614, 0.6960, 0.8795],
          [0.6558, 0.9617, 0.9539]]]),
 tensor([[[0.5592, 0.2741, 0.5490, 0.1815],
          [0.2798, 0.6735, 0.0871, 0.8809],
          [0.9003, 0.6567, 0.5135, 0.8920]],
 
         [[0.0264, 0.7002, 0.8478, 0.1054],
          [0.2772, 0.5632, 0.3883, 0.1901],
          [0.7082, 0.9757, 0.6436, 0.2072]],
 
         [[0.7371, 0.9987, 0.4855, 0.1724],
          [0.7548, 0.6671, 0.7721, 0.4141],
          [0.4191, 0.6423, 0.1100, 0.5531]]]))

In [187]:
torch.bmm(tensor1, tensor2)

tensor([[[0.8059, 0.9224, 0.4576, 1.1811],
         [0.5491, 0.4920, 0.3139, 0.6474]],

        [[0.9308, 2.0382, 1.7007, 0.4608],
         [0.0812, 0.3934, 0.4146, 0.0732]],

        [[1.6026, 1.9893, 1.1009, 0.9404],
         [1.6091, 1.9092, 1.1659, 1.0389]]])

### Broadcasting

In [188]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1 - x2
x1, x2, z

(tensor([[0.8071, 0.7818, 0.6377, 0.3608, 0.4805],
         [0.7157, 0.7902, 0.2119, 0.9482, 0.2568],
         [0.0471, 0.4824, 0.1981, 0.4940, 0.2750],
         [0.6720, 0.2285, 0.2737, 0.1402, 0.8384],
         [0.2107, 0.4492, 0.5409, 0.5114, 0.7867]]),
 tensor([[0.9075, 0.4454, 0.9298, 0.8243, 0.3197]]),
 tensor([[-0.1004,  0.3364, -0.2921, -0.4636,  0.1608],
         [-0.1919,  0.3448, -0.7178,  0.1239, -0.0629],
         [-0.8604,  0.0370, -0.7317, -0.3304, -0.0447],
         [-0.2355, -0.2169, -0.6561, -0.6841,  0.5187],
         [-0.6969,  0.0039, -0.3889, -0.3129,  0.4670]]))

In [189]:
z2 = x1 - x2.T
x1,x2.T,z2

(tensor([[0.8071, 0.7818, 0.6377, 0.3608, 0.4805],
         [0.7157, 0.7902, 0.2119, 0.9482, 0.2568],
         [0.0471, 0.4824, 0.1981, 0.4940, 0.2750],
         [0.6720, 0.2285, 0.2737, 0.1402, 0.8384],
         [0.2107, 0.4492, 0.5409, 0.5114, 0.7867]]),
 tensor([[0.9075],
         [0.4454],
         [0.9298],
         [0.8243],
         [0.3197]]),
 tensor([[-0.1004, -0.1258, -0.2698, -0.5468, -0.4270],
         [ 0.2703,  0.3448, -0.2334,  0.5028, -0.1886],
         [-0.8827, -0.4474, -0.7317, -0.4358, -0.6548],
         [-0.1523, -0.5958, -0.5506, -0.6841,  0.0141],
         [-0.1091,  0.1295,  0.2211,  0.1917,  0.4670]]))

In [190]:
s1 = torch.sum(x1, dim = 0) # total da coluna
s2 = torch.sum(x1, dim = 1) # total da linha
x1, s1, s2

(tensor([[0.8071, 0.7818, 0.6377, 0.3608, 0.4805],
         [0.7157, 0.7902, 0.2119, 0.9482, 0.2568],
         [0.0471, 0.4824, 0.1981, 0.4940, 0.2750],
         [0.6720, 0.2285, 0.2737, 0.1402, 0.8384],
         [0.2107, 0.4492, 0.5409, 0.5114, 0.7867]]),
 tensor([2.4526, 2.7320, 1.8623, 2.4546, 2.6375]),
 tensor([3.0679, 2.9229, 1.4965, 2.1528, 2.4989]))

In [191]:
values, indices = torch.max(x1, dim = 0)
values, indices

(tensor([0.8071, 0.7902, 0.6377, 0.9482, 0.8384]), tensor([0, 1, 0, 1, 3]))

In [192]:
torch.argmax(x1, dim = 0)

tensor([0, 1, 0, 1, 3])

In [193]:
torch.mean(x1, dim = 0)

tensor([0.4905, 0.5464, 0.3725, 0.4909, 0.5275])

In [194]:
torch.eq(x1,x1+1)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [195]:
values, indices = torch.sort(x1, dim = 0, descending = False)
x1, values

(tensor([[0.8071, 0.7818, 0.6377, 0.3608, 0.4805],
         [0.7157, 0.7902, 0.2119, 0.9482, 0.2568],
         [0.0471, 0.4824, 0.1981, 0.4940, 0.2750],
         [0.6720, 0.2285, 0.2737, 0.1402, 0.8384],
         [0.2107, 0.4492, 0.5409, 0.5114, 0.7867]]),
 tensor([[0.0471, 0.2285, 0.1981, 0.1402, 0.2568],
         [0.2107, 0.4492, 0.2119, 0.3608, 0.2750],
         [0.6720, 0.4824, 0.2737, 0.4940, 0.4805],
         [0.7157, 0.7818, 0.5409, 0.5114, 0.7867],
         [0.8071, 0.7902, 0.6377, 0.9482, 0.8384]]))

In [196]:
torch.clamp(x1, min = 0.5)

tensor([[0.8071, 0.7818, 0.6377, 0.5000, 0.5000],
        [0.7157, 0.7902, 0.5000, 0.9482, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.6720, 0.5000, 0.5000, 0.5000, 0.8384],
        [0.5000, 0.5000, 0.5409, 0.5114, 0.7867]])

In [197]:
x = torch.tensor([1,0,1,1,1], dtype = torch.bool)
torch.any(x), torch.all(x)

(tensor(True), tensor(False))

In [198]:
x.max(dim = 0)

torch.return_types.max(
values=tensor(True),
indices=tensor(0))

In [199]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
x

tensor([[0.1874, 0.0612, 0.7390, 0.0827, 0.1627, 0.9198, 0.0411, 0.1568, 0.8179,
         0.7167, 0.5540, 0.5075, 0.4937, 0.9051, 0.8369, 0.2020, 0.1622, 0.6543,
         0.5273, 0.9241, 0.5212, 0.2204, 0.5993, 0.7249, 0.5500],
        [0.8824, 0.7162, 0.2696, 0.2525, 0.4846, 0.6378, 0.0041, 0.1787, 0.4329,
         0.8359, 0.0360, 0.5236, 0.5124, 0.8589, 0.5763, 0.0776, 0.2972, 0.2223,
         0.6497, 0.5410, 0.6872, 0.5920, 0.5378, 0.8133, 0.3254],
        [0.3287, 0.9421, 0.7499, 0.0277, 0.8839, 0.8802, 0.9253, 0.2057, 0.1415,
         0.9542, 0.0830, 0.7380, 0.2884, 0.0719, 0.5229, 0.1295, 0.3944, 0.0133,
         0.3945, 0.3768, 0.6179, 0.4927, 0.9804, 0.4698, 0.6289],
        [0.0620, 0.9467, 0.1210, 0.2359, 0.3404, 0.8901, 0.3082, 0.4838, 0.6456,
         0.9619, 0.6650, 0.0660, 0.7969, 0.3927, 0.0171, 0.0831, 0.7598, 0.9895,
         0.2515, 0.7418, 0.4572, 0.2795, 0.8696, 0.2822, 0.6174],
        [0.0294, 0.5400, 0.7260, 0.5611, 0.2877, 0.5607, 0.2386, 0.6146, 0.0714,
       

In [200]:
x[0] , x[0] == x[0,:]

(tensor([0.1874, 0.0612, 0.7390, 0.0827, 0.1627, 0.9198, 0.0411, 0.1568, 0.8179,
         0.7167, 0.5540, 0.5075, 0.4937, 0.9051, 0.8369, 0.2020, 0.1622, 0.6543,
         0.5273, 0.9241, 0.5212, 0.2204, 0.5993, 0.7249, 0.5500]),
 tensor([True, True, True, True, True, True, True, True, True, True, True, True,
         True, True, True, True, True, True, True, True, True, True, True, True,
         True]))

In [201]:
x[:,0].shape

torch.Size([10])

In [202]:
x[1, 1:10]

tensor([0.7162, 0.2696, 0.2525, 0.4846, 0.6378, 0.0041, 0.1787, 0.4329, 0.8359])

In [203]:
x[1, 1] = 9
x[1, 1:10]

tensor([9.0000e+00, 2.6958e-01, 2.5255e-01, 4.8456e-01, 6.3779e-01, 4.0702e-03,
        1.7867e-01, 4.3294e-01, 8.3586e-01])

In [207]:
torch.arange(10)
indices = [2,15,24]
x[:, indices]

tensor([[0.7390, 0.2020, 0.5500],
        [0.2696, 0.0776, 0.3254],
        [0.7499, 0.1295, 0.6289],
        [0.1210, 0.0831, 0.6174],
        [0.7260, 0.5969, 0.2729],
        [0.6408, 0.8181, 0.5977],
        [0.9713, 0.6584, 0.0444],
        [0.4901, 0.6904, 0.1550],
        [0.9831, 0.8925, 0.5966],
        [0.2571, 0.1292, 0.6946]])

In [210]:
x = torch.rand((3,5))
rows = torch.tensor([1,0])
cols = torch.tensor([4,3])
x, x[rows,cols]

(tensor([[0.8349, 0.7069, 0.4799, 0.8289, 0.9486],
         [0.9923, 0.8319, 0.4292, 0.3191, 0.3869],
         [0.8117, 0.3450, 0.9604, 0.0801, 0.6420]]),
 tensor([0.3869, 0.8289]))

In [211]:
x = torch.arange(10)
x[(x < 2) | (x > 8)]

tensor([0, 1, 9])

In [213]:
x[x.remainder(2) != 0]

tensor([1, 3, 5, 7, 9])

In [214]:
torch.where(x > 5, x **2, x)

tensor([ 0,  1,  2,  3,  4,  5, 36, 49, 64, 81])

In [215]:
torch.tensor([0,0,1,1,3,3,3,5]).unique()

tensor([0, 1, 3, 5])

In [218]:
x, x1

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[0.8071, 0.7818, 0.6377, 0.3608, 0.4805],
         [0.7157, 0.7902, 0.2119, 0.9482, 0.2568],
         [0.0471, 0.4824, 0.1981, 0.4940, 0.2750],
         [0.6720, 0.2285, 0.2737, 0.1402, 0.8384],
         [0.2107, 0.4492, 0.5409, 0.5114, 0.7867]]))

In [219]:
x.ndimension(),x1.ndimension()

(1, 2)

In [220]:
x.numel() # número de elementos

10

## Reshape

In [222]:
x = torch.arange(9)
x.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [229]:
x.reshape(3,3), x.reshape(3,3).T

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 tensor([[0, 3, 6],
         [1, 4, 7],
         [2, 5, 8]]))

In [231]:
x.reshape(3,3).T.reshape(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [237]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
t1 = torch.cat( (x1,x2), dim = 0).shape
t2 = torch.cat( (x1,x2), dim = 1).shape
x1,x2,t1, t2

(tensor([[0.3692, 0.3798, 0.4529, 0.3657, 0.9759],
         [0.1588, 0.6576, 0.6988, 0.2759, 0.9625]]),
 tensor([[0.1829, 0.4525, 0.1918, 0.0590, 0.1737],
         [0.5170, 0.6667, 0.9943, 0.3018, 0.4230]]),
 torch.Size([4, 5]),
 torch.Size([2, 10]))

In [241]:
x1, x1.reshape(-1)

(tensor([[0.3692, 0.3798, 0.4529, 0.3657, 0.9759],
         [0.1588, 0.6576, 0.6988, 0.2759, 0.9625]]),
 tensor([0.3692, 0.3798, 0.4529, 0.3657, 0.9759, 0.1588, 0.6576, 0.6988, 0.2759,
         0.9625]))

In [243]:
torch.rand(3,2,5), torch.rand(3,2,5).reshape(3,-1)

(tensor([[[0.1551, 0.9620, 0.9540, 0.2518, 0.4784],
          [0.4664, 0.0590, 0.8042, 0.7606, 0.6208]],
 
         [[0.0207, 0.3301, 0.2971, 0.4463, 0.2536],
          [0.1890, 0.1117, 0.9890, 0.0878, 0.8271]],
 
         [[0.0694, 0.0727, 0.9309, 0.1627, 0.8396],
          [0.0156, 0.9559, 0.1513, 0.7824, 0.2172]]]),
 tensor([[0.6090, 0.0240, 0.0977, 0.2652, 0.7894, 0.5261, 0.8713, 0.0220, 0.7249,
          0.6506],
         [0.9732, 0.8168, 0.2000, 0.5593, 0.7682, 0.6986, 0.8301, 0.3222, 0.9144,
          0.9324],
         [0.6333, 0.1046, 0.5259, 0.0645, 0.8838, 0.1769, 0.9786, 0.9757, 0.1873,
          0.6488]]))

In [252]:
x = torch.rand(3,2,5)
x, x.permute(0, 2, 1)


(tensor([[[0.0104, 0.6846, 0.9660, 0.5554, 0.6896],
          [0.0984, 0.1527, 0.8882, 0.8178, 0.3924]],
 
         [[0.9049, 0.6969, 0.7852, 0.1662, 0.2093],
          [0.4035, 0.3830, 0.6614, 0.1939, 0.8366]],
 
         [[0.7029, 0.5918, 0.6626, 0.4602, 0.8593],
          [0.6085, 0.7743, 0.5680, 0.1222, 0.3405]]]),
 tensor([[[0.0104, 0.0984],
          [0.6846, 0.1527],
          [0.9660, 0.8882],
          [0.5554, 0.8178],
          [0.6896, 0.3924]],
 
         [[0.9049, 0.4035],
          [0.6969, 0.3830],
          [0.7852, 0.6614],
          [0.1662, 0.1939],
          [0.2093, 0.8366]],
 
         [[0.7029, 0.6085],
          [0.5918, 0.7743],
          [0.6626, 0.5680],
          [0.4602, 0.1222],
          [0.8593, 0.3405]]]))

In [255]:
x = torch.arange(10)
x.shape, x.unsqueeze(0).shape, x.unsqueeze(0).squeeze(0).shape

(torch.Size([10]), torch.Size([1, 10]), torch.Size([10]))

In [261]:
x.unsqueeze(0).unsqueeze(1)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [262]:
x.unsqueeze(0).unsqueeze(1).shape

torch.Size([1, 1, 10])